version: '3'

services:

  postgres:
    container_name:  postgres
    image:           postgres:11
    restart: "on-failure"
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - LC_ALL=C.UTF-8

  redis:
    container_name: redis
    image: redis:5
    restart: "always"
    command: redis-server --requirepass $REDIS_PASSWORD
    env_file: ./.env
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis